// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQXoJRuzXGI5h18Bbrnb4r1iRo3OZXgJc',
    appId: '1:169326548363:web:0628361e0312c787a94b8e',
    messagingSenderId: '169326548363',
    projectId: 'yalla-split',
    authDomain: 'yalla-split.firebaseapp.com',
    storageBucket: 'yalla-split.firebasestorage.app',
    measurementId: 'G-7X6R12GB74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAso7IYFwrXhVkm6U3LYwnBlS_XEUkSiWY',
    appId: '1:169326548363:android:d2d3cb8c0682670ca94b8e',
    messagingSenderId: '169326548363',
    projectId: 'yalla-split',
    storageBucket: 'yalla-split.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-dVC3syvl1poabMQSJgz_keXBKIxPt7U',
    appId: '1:169326548363:ios:e447c2ac37307e15a94b8e',
    messagingSenderId: '169326548363',
    projectId: 'yalla-split',
    storageBucket: 'yalla-split.firebasestorage.app',
    iosBundleId: 'com.example.yallasplitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-dVC3syvl1poabMQSJgz_keXBKIxPt7U',
    appId: '1:169326548363:ios:e447c2ac37307e15a94b8e',
    messagingSenderId: '169326548363',
    projectId: 'yalla-split',
    storageBucket: 'yalla-split.firebasestorage.app',
    iosBundleId: 'com.example.yallasplitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQXoJRuzXGI5h18Bbrnb4r1iRo3OZXgJc',
    appId: '1:169326548363:web:364b00381cc40b80a94b8e',
    messagingSenderId: '169326548363',
    projectId: 'yalla-split',
    authDomain: 'yalla-split.firebaseapp.com',
    storageBucket: 'yalla-split.firebasestorage.app',
    measurementId: 'G-5SE4F0P15W',
  );
}
